{% set name = "clingcon" %}
{% set version = "5.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 4b568475066e34be34110f481f7028b466c2b008e9ba41686e24ecbb468a40f2
  - path: patches

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make  # [unix]
    - cmake >=3.24.0
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - clingo >=5.5
  run:
    - python
    # clingo breaks the API with minor version increments
    - {{ pin_compatible('clingo', min_pin='x.x', max_pin='x.x') }}
    - cffi  # [python_impl == 'cpython']

test:
  commands:
    - clingcon --version
    - python -m clingcon --version
    - pip check
  requires:
    - pip

about:
  home: https://potassco.org/
  license: MIT
  summary: A solver for logic programs with linear constraints over integers.
  description: The clingcon solver extends the clingo ASP system with support for linear constraints over Integers.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
